"""FastMCP server registering the tool + resource surface.

Every tool is a thin wrapper around an existing ``operations/`` or
``store/`` function. Tool inputs are simple typed parameters; outputs are
JSON-serialised Pydantic models (via ``model_dump(mode="json")``) so the
calling agent sees the same shape an HTTP client of the FastAPI would.

Alongside the tools, the MCP *resources* primitive serves the session-start
memory digest at ``particles://digest/<store>`` —
``particles/mcp/resources.py`` owns its assembly and registration.

The server runs over stdio (the canonical local MCP install path) via
``particles mcp serve``. The sibling ``particles mcp tools`` command
dumps the registered surface as JSON for debugging without an MCP client
attached.

Tool bodies live under :mod:`particles.mcp.tools`, one file per domain
(query / particles / subjects / taxonomy / corpus / lint / diagnostics).
This module is the registration point: :data:`_TOOL_REGISTRATION_ORDER`
fixes the surface order — ``tests/mcp/tool-schema.json`` is pinned to it,
so changing the order is an intentional contract change that needs a
golden refresh.
"""

from __future__ import annotations

import functools
import logging
from collections.abc import Callable
from typing import Any

from mcp.server.fastmcp import FastMCP
from opentelemetry import trace

from particles.config import get_config
from particles.mcp.resources import register_digest_resources
from particles.mcp.tools.corpus import corpus_links_suggest, list_corpus_entries
from particles.mcp.tools.diagnostics import quality_report
from particles.mcp.tools.events import event_show, events_list
from particles.mcp.tools.graph import graph_view
from particles.mcp.tools.links_suggest import links_suggest
from particles.mcp.tools.lint import lint
from particles.mcp.tools.particles import particle_search, particle_show, particles_list
from particles.mcp.tools.query import query
from particles.mcp.tools.subjects import subjects_list, subjects_search, subjects_show
from particles.mcp.tools.taxonomy import list_taxonomies
from particles.mcp.tools.write import (
    deposit_text,
    link_add,
    link_remove,
    particle_assert,
    particle_retract,
    particle_supersede,
    particle_tag,
    particle_untag,
)

log = logging.getLogger(__name__)

SERVER_NAME = "particles"
SERVER_INSTRUCTIONS = (
    "Particles SDK — read-only access to an epistemic knowledge store. Use "
    "`query` for natural-language questions with optional tag/subject filters; "
    "`particle_show` / `subjects_show` to inspect individual records; "
    "`lint` and `quality_report` for diagnostics; `links_suggest` to find "
    "candidate co-evidential (duplicate-claim) pairs within a Subject; "
    "`corpus_links_suggest` to rank undeposited but frequently-cited URLs as "
    "deposit suggestions; "
    "`events_list` / `event_show` to read the operator event log — the audit "
    "trail of operator decisions (retractions, subject splits/merges, trust "
    "changes, reviews, …); `graph_view` for a scoped epistemic subgraph "
    "(subject neighbourhood or query retrieval set — the picture of the "
    "knowledge consulted, with server-computed confidence/status/contested "
    "encodings). Read tools are always available; the write tools "
    "(`particle_assert` / `particle_supersede` / `particle_retract` / "
    "`deposit_text`) appear only when a store is write-enabled "
    "(mcp.write.enabled_stores). The `particles://digest/<store>` "
    "resource is the session-start memory digest — one line per "
    "ACTIVE belief, ranked by effective confidence, contested beliefs flagged; "
    "read it to recall a store's standing context."
)

# Registration order is part of the contract — `tests/mcp/tool-schema.json`
# is generated by `particles mcp tools` and pins this order. Re-order only
# with an intentional golden refresh.
_TOOL_REGISTRATION_ORDER: tuple[Callable[..., Any], ...] = (
    query,
    particle_show,
    particles_list,
    particle_search,
    subjects_list,
    subjects_search,
    subjects_show,
    list_taxonomies,
    list_corpus_entries,
    lint,
    quality_report,
    links_suggest,
    corpus_links_suggest,
    events_list,
    event_show,
    graph_view,
)

# write surface. Registered only when at least one store is
# write-enabled (see build_server), so a stock install keeps the read-only
# surface it had and the default golden tool-schema is unchanged.
_WRITE_TOOL_REGISTRATION_ORDER: tuple[Callable[..., Any], ...] = (
    particle_assert,
    particle_supersede,
    particle_retract,
    deposit_text,
    link_add,
    link_remove,
    particle_tag,
    particle_untag,
)


_mcp_tracer = trace.get_tracer("particles.mcp")


def _traced_tool(fn: Callable[..., Any]) -> Callable[..., Any]:
    """Wrap an MCP tool so each invocation gets a root ``mcp.<tool>`` span.

    Without a per-call span, a tool's downstream store / httpx work is parentless
    and fragments into separate single-span traces (the same issue the CLI root
    span fixes). ``functools.wraps`` preserves the signature, annotations, and
    docstring FastMCP introspects to build the tool schema, so the registered
    surface — and the golden tool-schema test — is unchanged. Uses the OTel API
    directly (a no-op when observability is off). All registered tools are
    ``async def``.
    """

    @functools.wraps(fn)
    async def wrapper(*args: Any, **kwargs: Any) -> Any:
        with _mcp_tracer.start_as_current_span(f"mcp.{fn.__name__}"):
            return await fn(*args, **kwargs)

    return wrapper


def build_server() -> FastMCP:
    """Construct a FastMCP server with the tool surface registered.

    The read tools are always registered. The write tools are added
    only when ``mcp.write.enabled_stores`` is non-empty (default-deny, §5) — a
    stock install exposes exactly the read-only surface it had.

    Separated from ``main`` so unit tests can inspect / invoke the tool
    handlers without spawning the stdio transport.
    """
    server: FastMCP = FastMCP(name=SERVER_NAME, instructions=SERVER_INSTRUCTIONS)
    for fn in _TOOL_REGISTRATION_ORDER:
        server.tool()(_traced_tool(fn))
    if get_config().mcp.write.enabled_stores:
        for fn in _WRITE_TOOL_REGISTRATION_ORDER:
            server.tool()(_traced_tool(fn))
    # session-start recall: the digest resource template is always
    # available (a read-only view of any store); concrete per-store digests are
    # listed for the write-enabled / opted-in memory stores (§2).
    register_digest_resources(server)
    return server


def main() -> None:
    """Entry point for ``particles mcp serve``.

    Builds the server and runs it over stdio. The calling MCP client
    (Claude Code, Claude Desktop, etc.) spawns this as a child process
    and speaks the MCP wire protocol over the child's stdin/stdout.
    """
    # Bootstrap observability for the MCP process. No-op unless enabled
    # + the `otel` extra is installed; when on, the tool handlers' downstream
    # store / httpx work is traced like any other engine path.
    from particles.observability import setup_observability

    setup_observability()
    server = build_server()
    server.run(transport="stdio")


if __name__ == "__main__":
    main()
