"""Documentation-projection pipeline — render a manifest into a cited doc.

For each derived section, in manifest order:

1. **Select** candidate particles by running the section's binding through
   ``operations.query.retrieve_ranked`` with the current-truth filter pinned
   (:func:`_select_section_particles`, §3).
2. **Synthesise** the section as cited prose via the ``article_synthesis`` engine
   (Layer-A/B guard rails + deterministic fallback), or — in the drift-gate /
   key-free mode — emit a deterministic structured listing of the selection.
3. **Assemble** the rendered sections and the mechanical blocks into the full
   document in manifest order.

The **drift gate** (``project <manifest> --check``) regenerates the document in
deterministic mode and compares it to the committed snapshot: deterministic
selection + document structure hard-fail on drift; LLM prose drift is advisory
(fork #3). Deterministic mode needs neither an API key nor an embedding
model, so the gate runs in CI.

Engine layer: reads the store, runs query + synthesis, calls the LLM.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from pathlib import Path

from sqlalchemy.ext.asyncio import AsyncSession

from particles.config import get_config
from particles.core.schema import Particle, QueryRequest
from particles.operations.abstraction import projection_suppressed_premise_ids
from particles.operations.projection.manifest import (
    DerivedSection,
    DocManifest,
    MechanicalBlock,
)
from particles.operations.query import retrieve_ranked
from particles.operations.query.effective_confidence import score_effective_confidence
from particles.render.article_synthesis import (
    _CITATION_RE,
    SectionTopic,
    _short_id,
    compute_input_hash,
    render_article,
    split_rendered_article,
)
from particles.render.markdown import (
    PROJECTED_BEGIN_RE_TMPL,
    PROJECTED_BEGIN_TMPL,
    PROJECTED_END_RE_TMPL,
    PROJECTED_END_TMPL,
    SOURCES_TRAILER_RE,
    find_projected_regions,
    format_memory_bullet,
    format_sources_trailer,
)
from particles.store.particle_store import (
    get_active_particle_by_id_or_prefix,
    get_inconsistency_backrefs,
)

log = logging.getLogger(__name__)


class SelectPinError(ValueError):
    """A ``select.allow`` pin could not be resolved to an ACTIVE particle.

    Raised when a derived section's ``select.allow`` id matches **no ACTIVE
    particle** (retracted, superseded, or never existed): a pin that points at
    nothing is an author mistake, not silent doc drift, so the projection fails
    loudly rather than render a section quietly missing its pinned claim. The
    message names the offending id and section — mirroring :class:`SpliceError`
     — so an operator can re-pin the successor id or widen the cage.

    A stale ``select.deny`` id, by contrast, is only a warning (its exclusion is
    already satisfied), never this error.
    """


#: Non-volatile banner opening every projected document. Carries no timestamp so
#: a regeneration is byte-stable — the drift gate diffs the whole file.
_BANNER = (
    "<!-- Generated by `particles project` from the {name} manifest.\n"
    "     This document is a cited view of the particle store. Edit the manifest\n"
    "     (docs/projection/{name}.yaml) or the claims in the store, not this file. -->\n"
)

#: (particle, effective_confidence) for one selected candidate.
Selected = tuple[Particle, float]


async def _select_section_particles(
    session: AsyncSession,
    section: DerivedSection,
    *,
    use_embeddings: bool,
) -> list[Selected]:
    """Select a derived section's candidate particles under the current-truth filter.

    Runs the section binding through ``retrieve_ranked``. ``subjects`` are
    resolved by canonical name and queried one at a time (``QueryRequest`` carries
    a single ``subject_id``); the per-subject results are merged, de-duplicated by
    particle id, and re-ranked by effective confidence with a deterministic
    id tie-break. When no ``subjects`` are given the binding is a single
    tag / query-scoped retrieval across the store.

    Current-truth selection is pinned on the request:
    ``include_non_asserted=False`` (ASSERTED polarity only, cap. 1),
    ``include_document_meta=False`` (no apparatus). ``DOCUMENT_SUPERSEDED``
    needs no explicit flag: it is a *status reason* that demotes a claim out of
    ``ACTIVE``, and the candidate load is ACTIVE-only, so superseded claims are
    already excluded (cap. 2).
    """
    from particles.store.subject_store import find_by_name

    subject_ids: list[str | None]
    if section.subjects:
        subject_ids = []
        for name in section.subjects:
            subj = await find_by_name(session, name)
            if subj is None:
                log.warning(
                    "projection: section %r binds subject %r, which is not in the store; "
                    "skipping that subject",
                    section.title,
                    name,
                )
                continue
            subject_ids.append(subj.id)
        if not subject_ids:
            return []
    else:
        subject_ids = [None]

    merged: dict[str, Selected] = {}
    for sid in subject_ids:
        request = QueryRequest(
            question=section.topic_query,
            tags=section.tags,
            subject_id=sid,
            top_k=section.top_k,
            min_confidence=section.min_confidence,
            # Current-truth filter — pinned, not caller-tunable.
            include_non_asserted=False,
            include_document_meta=False,
        )
        # the projection is a projection/digest-path consumer, so the
        # usefulness factor is folded into ranking *inside* `retrieve_ranked`,
        # before its top_k cut — an acted-upon belief tied at the confidence
        # ceiling is promoted *into* the rendered set (not merely reordered
        # within an already-cut top_k). The semantic-search `query` path never
        # calls `retrieve_ranked`, so its ranking is untouched.
        scored = await retrieve_ranked(
            session,
            request,
            use_embeddings=use_embeddings,
            code_symbol_rank_weight=section.code_symbol_rank_weight,
            apply_utility=True,
            apply_owner=True,
        )
        for particle, _sim, eff in scored:
            if particle.id not in merged:
                merged[particle.id] = (particle, eff)

    # never spend projection budget on both an abstraction and
    # its premises — premises of an ACTIVE derived particle drop out of the
    # cage (ranking-side only; they stay ACTIVE and queryable, and reappear
    # here automatically if the derived particle is ever retired). An explicit
    # ``select.allow`` pin overrides the suppression: the allow step below
    # re-loads pins by id after this filter, mirroring the pin top_k exemption.
    suppressed = await projection_suppressed_premise_ids(session)
    if suppressed:
        merged = {pid: pe for pid, pe in merged.items() if pid not in suppressed}

    return await _apply_select(session, section, merged)


def _strip_pin_prefix(pin: str) -> str:
    """Strip a leading ``p-`` / ``p:`` display prefix from a manifest pin id.

    The ``select.allow|deny`` ids are written in the ``p-<shortid>`` display
    form (the sources trailer / ``particle_show`` form) or the full store id;
    the resolver works on the bare id. Kept local to the Engine projection layer
    rather than importing the ``api/cli`` helper (that would be an upward import
    across the layering contract).
    """
    s = pin.strip()
    for prefix in ("p-", "p:"):
        if s.startswith(prefix):
            return s[len(prefix) :]
    return s


async def _apply_select(
    session: AsyncSession,
    section: DerivedSection,
    cage: dict[str, Selected],
) -> list[Selected]:
    """Post-process the cage's selection with ``select.deny`` / ``select.allow``.

    Applied in the fixed order: ``deny`` subtracts, ``allow`` unions (loading the
    pinned ACTIVE particle directly by id), then the merged set is re-ranked by
    effective confidence and truncated to ``top_k`` — with ``allow``-pinned ids
    **exempt from the cut** (a pin ``top_k`` could silently drop is a footgun).
    Pure, deterministic id arithmetic over the already-deterministic cage result,
    so ``required_particle_ids`` and the drift snapshot pick up the resolved
    selection for free.

    A stale ``allow`` id (no ACTIVE particle) is a hard :class:`SelectPinError`;
    a stale ``deny`` id only warns (its exclusion is already satisfied).
    """
    select = section.select

    # Step 2 — deny subtracts (post-filter over the cage's resolved ids).
    deny_full = {_strip_pin_prefix(d) for d in select.deny}
    if deny_full:
        kept: dict[str, Selected] = {}
        matched_denies: set[str] = set()
        for pid, pe in cage.items():
            denied_by = next((d for d in deny_full if pid == d or pid.startswith(d)), None)
            if denied_by is not None:
                matched_denies.add(denied_by)
            else:
                kept[pid] = pe
        merged = kept
        # Stale deny = warn (its exclusion is already satisfied).
        for d in sorted(deny_full - matched_denies):
            log.warning(
                "projection: section %r select.deny id %r matched no current candidate; "
                "its exclusion is already satisfied (dead manifest cruft to clean up)",
                section.title,
                d,
            )
    else:
        merged = dict(cage)

    # Step 3 — allow unions: load each missing pin's ACTIVE particle by id.
    allow_ids: set[str] = set()
    for raw in select.allow:
        pin = _strip_pin_prefix(raw)
        existing = next((pid for pid in merged if pid == pin or pid.startswith(pin)), None)
        if existing is not None:
            allow_ids.add(existing)
            continue
        particle = await get_active_particle_by_id_or_prefix(session, pin)
        if particle is None:
            # Stale allow = hard error.
            raise SelectPinError(
                f"section {section.title!r} select.allow id {raw!r} resolves to no ACTIVE "
                "particle (retracted, superseded, or never existed). Re-pin the successor "
                "id or widen the section's cage."
            )
        # Compute effective confidence the same way the selector does — the
        # full formula, minus the embedding step,
        # with the usefulness factor so a pin ranks against the
        # utility-adjusted cage on the same scale.
        # Scored on the *same* scale as the ranked set below (step 4
        # re-ranks pins and non-pins together), so both recall addends apply:
        # utility and owner-relevance.
        eff_map = await score_effective_confidence(
            session, [particle], apply_utility_factor=True, apply_owner_lens=True
        )
        merged[particle.id] = (particle, eff_map.get(particle.id, particle.confidence.value))
        allow_ids.add(particle.id)

    # Step 4 — re-rank by the existing key, then truncate to top_k with the
    # allow-pinned ids exempt from the cut (step 4).
    ranked = sorted(merged.values(), key=lambda pe: (-pe[1], pe[0].id))
    if len(ranked) <= section.top_k:
        return ranked
    out: list[Selected] = []
    extra_allows: list[Selected] = []
    for pe in ranked:
        if len(out) < section.top_k:
            out.append(pe)
        elif pe[0].id in allow_ids:
            extra_allows.append(pe)
    # Place exempt pins at their natural ranked position relative to the kept set.
    if extra_allows:
        out = sorted(out + extra_allows, key=lambda pe: (-pe[1], pe[0].id))
    return out


async def select_section_particles(
    session: AsyncSession,
    section: DerivedSection,
    *,
    use_embeddings: bool = False,
) -> list[Selected]:
    """One derived section's ranked selection — the public seam over
    :func:`_select_section_particles`.

    Defaults to the deterministic, key-free ranking (``use_embeddings=False``)
    — the same selection the drift gate snapshots. Consumed by the ``scope=projection`` graph render (``operations.graph_view``), which must
    stay reproducible without an API key.
    """
    return await _select_section_particles(session, section, use_embeddings=use_embeddings)


async def required_particle_ids(session: AsyncSession, manifest: DocManifest) -> set[str]:
    """The ACTIVE particle ids a manifest's derived sections currently select.

    The union of each derived section's deterministic, key-free selection
    (``use_embeddings=False``) — i.e. the particles this projection's prose
    *depends on*. Feeds the ``projection_blocking`` curation signal
    : a card whose belief is in this set is worth tending first,
    because fixing it changes a generated doc. Mechanical blocks bind no
    particles and are skipped.
    """
    out: set[str] = set()
    for section in manifest.sections:
        if isinstance(section, DerivedSection):
            selected = await _select_section_particles(session, section, use_embeddings=False)
            out.update(particle.id for particle, _eff in selected)
    return out


def _sources_trailer(short_ids: list[str]) -> str:
    """The per-section provenance trailer (fork #2 = clean prose).

    Verify-only clean prose carries no inline ``[n]`` markers; provenance is a
    single HTML-comment trailer listing the cited / selected particle short-ids
    (sorted, de-duplicated), so the README stays clean while every statement
    remains traceable. Returns ``""`` for an empty list. Formatting is shared
    with the freshness check via ``render.markdown``.
    """
    return format_sources_trailer(short_ids)


def _deterministic_section_body(particles: list[Selected]) -> str:
    """A reproducible, key-free listing of a section's selected particles.

    Used by the ``--without-synthesis`` render and the drift gate: one bullet per
    selected particle (in rank order) carrying its content, short-id, and
    effective confidence — all deterministic given the store — plus the sources
    trailer. This is the gate's selection-and-structure fingerprint.
    """
    lines = [
        f"- {particle.content} `p-{_short_id(particle.id)}` _(confidence {eff:.2f})_"
        for particle, eff in particles
    ]
    short_ids = [_short_id(particle.id) for particle, _eff in particles]
    return "\n".join(lines) + "\n\n" + _sources_trailer(short_ids)


@dataclass
class _BulletSectionPart:
    """A ``render: bullets`` section held un-rendered so the budget can trim it.

    Per the projection rule (§4 / §5): the section renders as deterministic ranked bullets
    (digest-entry formatting, contested flags via INCONSISTENCY backrefs) plus
    a sources trailer. Keeping the selected entries structured — instead of a
    flat string — lets :func:`_apply_budget` drop the lowest-effective-
    confidence non-pinned entries and re-render, so truncation is rank-order
    by construction.
    """

    header: str
    #: ``(particle, effective_confidence, contested_by_inconsistency_id,
    #: contested_bases)`` — the last two feed the bullet flag; bases
    #: are empty when no badge fired (or the badge is disabled), which renders
    #: the pre-badge inconsistency-only flag unchanged.
    entries: list[tuple[Particle, float, str | None, tuple[str, ...]]]
    #: Resolved ids of ``select.allow`` pins — exempt from budget truncation.
    pinned: frozenset[str]

    def render(self) -> str:
        if not self.entries:
            return f"{self.header}_No current particles match this section's binding._\n"
        lines = [
            format_memory_bullet(
                p.content,
                _short_id(p.id),
                _short_id(inc) if inc else None,
                contested_bases=bases,
            )
            for p, _eff, inc, bases in self.entries
        ]
        trailer = _sources_trailer([_short_id(p.id) for p, _eff, _inc, _bases in self.entries])
        return f"{self.header}" + "\n".join(lines) + "\n\n" + trailer


def _bullet_section_part(
    section: DerivedSection,
    particles: list[Selected],
    *,
    header: str,
    backrefs: dict[str, str],
    badges: dict[str, tuple[str, ...]],
) -> _BulletSectionPart:
    """Build the structured bullet part for one ``render: bullets`` section.

    ``badges`` maps particle id → the composed badge's fired bases;
    empty (or an id absent from it) renders the pre-badge inconsistency-only
    flag from ``backrefs`` unchanged.
    """
    pin_bodies = {_strip_pin_prefix(a) for a in section.select.allow}
    pinned = frozenset(
        p.id
        for p, _eff in particles
        if any(p.id == body or p.id.startswith(body) for body in pin_bodies)
    )
    entries = [(p, eff, backrefs.get(p.id), badges.get(p.id, ())) for p, eff in particles]
    return _BulletSectionPart(header=header, entries=entries, pinned=pinned)


async def _bullet_badges(
    session: AsyncSession,
    particles: list[Selected],
    backrefs: dict[str, str],
) -> dict[str, tuple[str, ...]]:
    """Fired badge bases per rendered bullet entry (top-N only).

    Composes the contested badge for exactly the particles a bullets section
    will render. Returns ``{}`` when ``contestedness.badge_enabled`` is off —
    restoring the pre-badge inconsistency-only flag exactly. The composition is
    deterministic (no LLM, no embeddings), so the sentinel-region render stays
    byte-stable for a given store state.
    """
    if not particles or not get_config().contestedness.badge_enabled:
        return {}
    from particles.operations.query.contested import compute_contested_badges

    targets = [p for p, _eff in particles]
    badges = await compute_contested_badges(session, targets, backrefs=backrefs)
    return {
        p.id: tuple(badge.bases)
        for (p, _eff), badge in zip(particles, badges, strict=True)
        if badge is not None
    }


def _assemble_splice_parts(parts: list[str | _BulletSectionPart]) -> str:
    rendered = [part if isinstance(part, str) else part.render() for part in parts]
    return "\n".join(p.rstrip("\n") for p in rendered).strip("\n") + "\n"


def _apply_budget(
    parts: list[str | _BulletSectionPart],
    *,
    max_lines: int | None,
    max_bytes: int | None,
) -> str:
    """Enforce the manifest's document budget on the assembled splice body.

    Rank-order truncation: while the assembled body exceeds ``max_lines`` /
    ``max_bytes``, the globally lowest-effective-confidence **bullet** entry
    (deterministic id tie-break, matching the selection's rank order) is
    dropped and the body re-assembled. ``select.allow`` pins are exempt
    ; prose sections and mechanical blocks are never truncated —
    if the budget still cannot be met once every droppable bullet is gone, the
    over-budget body is returned with a warning rather than corrupting prose.
    """
    document = _assemble_splice_parts(parts)
    if max_lines is None and max_bytes is None:
        return document

    def over_budget(doc: str) -> bool:
        if max_lines is not None and len(doc.splitlines()) > max_lines:
            return True
        return max_bytes is not None and len(doc.encode("utf-8")) > max_bytes

    while over_budget(document):
        droppable: list[tuple[float, str, _BulletSectionPart, int]] = [
            (eff, p.id, part, i)
            for part in parts
            if isinstance(part, _BulletSectionPart)
            for i, (p, eff, _inc, _bases) in enumerate(part.entries)
            if p.id not in part.pinned
        ]
        if not droppable:
            log.warning(
                "projection: document budget (max_lines=%s, max_bytes=%s) cannot be met "
                "— every remaining line is pinned or non-bullet content; rendering over budget",
                max_lines,
                max_bytes,
            )
            break
        # Rank order is (-eff, id); the last-ranked entry is the one with the
        # lowest effective confidence, greatest id among ties — drop it first.
        _eff, _pid, part, idx = max(droppable, key=lambda d: (-d[0], d[1]))
        del part.entries[idx]
        document = _assemble_splice_parts(parts)
    return document


#: ``[[wiki-link]]`` / ``[[target|alias]]`` — the vault-exporter link form the
#: synthesiser emits around subject names. A spliced host file (README,
#: MEMORY.md) is plain Markdown, not a wiki vault, so the splice paths render
#: these as plain text; the full-document render keeps them for
#: the vault-adjacent preview flows.
_WIKI_LINK_RE = re.compile(r"\[\[([^\[\]|]+?)(?:\|([^\[\]]+?))?\]\]")


def strip_wiki_links(text: str) -> str:
    """Render ``[[wiki-links]]`` as plain text for a plain-Markdown host.

    ``[[Target]]`` → ``Target``; ``[[Target|alias]]`` → ``alias``. HTML-comment
    trailers and code spans are untouched (neither contains the bracket form).
    """
    return _WIKI_LINK_RE.sub(lambda m: m.group(2) or m.group(1), text)


def _clean_prose(prose: str) -> tuple[str, list[str]]:
    """Strip inline ``[^p-xxxx]`` citation markers, returning (clean_prose, cited_ids).

    Layer A/B already guaranteed every claim cites a real particle at synthesis
    time; the outward doc renders clean prose with provenance moved
    to the sources trailer. Removes the markers and tidies the
    space-before-the-marker / space-before-punctuation the removal leaves behind.
    """
    cited = [m.group(1).lower() for m in _CITATION_RE.finditer(prose)]
    stripped = _CITATION_RE.sub("", prose)
    stripped = re.sub(r"[ \t]+([.,;:!?])", r"\1", stripped)
    stripped = re.sub(r"[ \t]{2,}", " ", stripped)
    stripped = re.sub(r"[ \t]+\n", "\n", stripped)
    return stripped.strip(), cited


async def _synthesised_section_body(
    session: AsyncSession,
    section: DerivedSection,
    particles: list[Selected],
    manifest_name: str,
    framing: str | None = None,
) -> tuple[str, bool]:
    """Render a derived section as cited prose via the article-synthesis engine.

    Returns ``(body, used_synthesis)``. On synthesis success the body is clean
    prose + a sources trailer of the *cited* particles. When synthesis is
    unavailable (no key, LLM error, or a Layer-A/B failure), falls back to the
    deterministic listing so the section still renders.

    The section's ``direction`` / ``flowing`` (2) and the manifest's
    ``framing`` (§3) steer the synthesis prompt only; selection and the
    deterministic fallback are unaffected.
    """
    plist = [p for p, _ in particles]
    eff = {p.id: ec for p, ec in particles}
    needed_entry_ids = {
        ref.corpus_entry_id for p in plist for ref in p.provenance if ref.corpus_entry_id
    }

    from particles.corpus.store import get_entry_uri_map

    corpus_uris = await get_entry_uri_map(session, needed_entry_ids)
    topic = SectionTopic(id=f"{manifest_name}:{section.title}", canonical_name=section.title)
    wiki_cfg = get_config().wiki

    rendered, used_synthesis = await render_article(
        subject=topic,
        particles=plist,
        eff=eff,
        input_hash=compute_input_hash(plist),
        corpus_uris=corpus_uris,
        max_tokens=wiki_cfg.max_tokens,
        layer_b_enabled=wiki_cfg.layer_b_enabled,
        # per-section authoring brief + flowing-prose flag + the
        # document-level framing spine steer the synthesis prompt (defaults
        # reproduce today's behaviour).
        direction=section.direction,
        flowing=section.flowing,
        framing=framing,
        # No shared cache: a SectionTopic id is not a real Subject id,
        # so it must not be written to the per-subject synthesis cache.
        session=None,
    )
    if not used_synthesis:
        return _deterministic_section_body(particles), False

    _fm, _h1, prose, _refs = split_rendered_article(rendered)
    clean, cited = _clean_prose(prose)
    trailer = _sources_trailer(cited)
    body = clean + ("\n\n" + trailer if trailer else "\n")
    return body, True


def _render_block(block: MechanicalBlock, base_dir: Path) -> str:
    """Read a mechanical block's hand-authored fragment, spliced verbatim.

    The path is resolved relative to the manifest's directory. Raises
    ``FileNotFoundError`` when the fragment is missing — a manifest must not
    reference a block that does not exist.
    """
    path = Path(block.block)
    if not path.is_absolute():
        path = base_dir / path
    return path.read_text(encoding="utf-8").strip() + "\n"


@dataclass(frozen=True)
class ProjectionResult:
    """A rendered projection plus whether any section used LLM synthesis."""

    document: str
    used_synthesis: bool


#: Sentinel format strings + parse regexes. Hoisted to the
#: Client-layer ``particles.render.markdown`` so the harvest-side
#: strip imports them downward; these aliases keep this module's call sites
#: (and its documented back-compat surface) unchanged.
_SPLICE_BEGIN = PROJECTED_BEGIN_TMPL
_SPLICE_END = PROJECTED_END_TMPL
_SPLICE_BEGIN_RE_TMPL = PROJECTED_BEGIN_RE_TMPL
_SPLICE_END_RE_TMPL = PROJECTED_END_RE_TMPL


class SpliceError(ValueError):
    """A block-splice could not be performed against the target file.

    Raised when the named region is missing, when a BEGIN sentinel has no
    matching END (or vice versa), or when the region appears more than once.
    The message names the region and the failure so an operator can fix the
    target file by hand.
    """


def splice_region(existing: str, region: str, new_body: str, *, manifest: str) -> str:
    """Replace the text between a named sentinel pair, preserving everything else.

    The block-splice contract. ``existing`` is the full current text of a
    hand-authored file carrying exactly one sentinel pair for ``region``::

        <!-- BEGIN PROJECTED: architecture (manifest: docs/projection/x.yaml) -->
        … old projected content …
        <!-- END PROJECTED: architecture -->

    Returns ``existing`` with the content *between* the sentinels replaced by
    ``new_body`` (the sentinels themselves are rewritten so the ``manifest:``
    attribution stays current), and all content outside the pair preserved
    byte-for-byte. The operation is idempotent: re-splicing a file that already
    carries the pair replaces the body cleanly and keeps a single pair.

    Raises :class:`SpliceError` when the region is missing, when a BEGIN has no
    matching END, or when ``region`` appears more than once (each is a target-file
    authoring mistake, not a recoverable case).
    """
    begin_re = re.compile(_SPLICE_BEGIN_RE_TMPL.format(region=re.escape(region)))
    end_re = re.compile(_SPLICE_END_RE_TMPL.format(region=re.escape(region)))

    begins = list(begin_re.finditer(existing))
    ends = list(end_re.finditer(existing))

    if len(begins) > 1 or len(ends) > 1:
        raise SpliceError(
            f"projection region {region!r} appears more than once in the target file "
            f"({len(begins)} BEGIN / {len(ends)} END sentinels); a region must be unique."
        )
    if not begins and not ends:
        raise SpliceError(
            f"projection region {region!r} not found in the target file. Add the sentinel "
            f"pair:\n  {_SPLICE_BEGIN.format(region=region, manifest=manifest)}\n  "
            f"{_SPLICE_END.format(region=region)}"
        )
    if not begins:
        raise SpliceError(
            f"projection region {region!r} has an END sentinel but no matching BEGIN."
        )
    if not ends:
        raise SpliceError(f"projection region {region!r} has a BEGIN sentinel but no matching END.")

    begin, end = begins[0], ends[0]
    if end.start() < begin.end():
        raise SpliceError(
            f"projection region {region!r} has its END sentinel before its BEGIN sentinel."
        )

    new_begin = _SPLICE_BEGIN.format(region=region, manifest=manifest)
    new_end = _SPLICE_END.format(region=region)
    body = new_body.strip("\n")
    replacement = f"{new_begin}\n{body}\n{new_end}" if body else f"{new_begin}\n{new_end}"
    return existing[: begin.start()] + replacement + existing[end.end() :]


async def project_document(
    session: AsyncSession,
    manifest: DocManifest,
    *,
    base_dir: Path,
    synthesize: bool,
) -> ProjectionResult:
    """Render a manifest into one Markdown document.

    ``synthesize=True`` renders each derived section as LLM-cited clean prose
    (requires an API key; falls back per-section to the deterministic listing on
    failure). ``synthesize=False`` is the deterministic, key-free, embedding-free
    render used by ``--without-synthesis`` and the drift gate — byte-stable for a
    given store, which is what makes the gate enforceable.
    """
    parts: list[str] = [_BANNER.format(name=manifest.name)]
    any_synth = False
    backrefs: dict[str, str] | None = None

    for section in manifest.sections:
        if isinstance(section, MechanicalBlock):
            parts.append(_render_block(section, base_dir))
            continue

        # A bullets section is deterministic by definition:
        # embedding-free selection, no synthesis, regardless of `synthesize`.
        bullets = section.render == "bullets"
        particles = await _select_section_particles(
            session, section, use_embeddings=synthesize and not bullets
        )
        header = f"## {section.title}\n"
        if not particles:
            log.warning("projection: section %r selected no particles", section.title)
            parts.append(f"{header}\n_No current particles match this section's binding._\n")
            continue

        if bullets:
            if backrefs is None:
                backrefs = await get_inconsistency_backrefs(session)
            badges = await _bullet_badges(session, particles, backrefs)
            body = _bullet_section_part(
                section, particles, header="", backrefs=backrefs, badges=badges
            ).render()
        elif synthesize:
            body, used = await _synthesised_section_body(
                session, section, particles, manifest.name, framing=manifest.framing
            )
            any_synth = any_synth or used
        else:
            body = _deterministic_section_body(particles)
        parts.append(f"{header}\n{body.rstrip()}\n")

    document = "\n".join(part.rstrip("\n") for part in parts) + "\n"
    return ProjectionResult(document=document, used_synthesis=any_synth)


async def project_splice_body(
    session: AsyncSession,
    manifest: DocManifest,
    *,
    base_dir: Path,
    synthesize: bool,
) -> ProjectionResult:
    """Render a manifest's *body* for splicing into a sentinel region.

    Like :func:`project_document` but tailored for the block-splice write mode:
    it omits the document banner (the host file is hand-authored) and, for a
    single-section manifest, omits the ``## <title>`` heading — the host file's
    hand-authored heading above the sentinels owns it (the ADR §1 layout puts
    ``## Architecture`` *outside* the block). A multi-section manifest keeps its
    per-section headings, since the block then carries more than one section.

    The README-architecture slice is single-section, so the spliced region is
    pure projected prose plus its sources trailer — exactly what sits under the
    hand-authored ``## Architecture`` heading.
    """
    single_section = len(manifest.sections) == 1
    parts: list[str | _BulletSectionPart] = []
    any_synth = False
    backrefs: dict[str, str] | None = None

    for section in manifest.sections:
        if isinstance(section, MechanicalBlock):
            parts.append(_render_block(section, base_dir))
            continue
        header = "" if single_section else f"## {section.title}\n\n"
        part, used, backrefs = await _derived_section_part(
            session,
            section,
            manifest,
            synthesize=synthesize,
            header=header,
            backrefs=backrefs,
        )
        any_synth = any_synth or used
        parts.append(part)

    # Document budget: enforced by the splice renderer only —
    # rank-order truncation of bullet entries, `select.allow` pins exempt.
    document = _apply_budget(parts, max_lines=manifest.max_lines, max_bytes=manifest.max_bytes)
    # A spliced host file is plain Markdown, not a wiki vault.
    return ProjectionResult(document=strip_wiki_links(document), used_synthesis=any_synth)


async def _derived_section_part(
    session: AsyncSession,
    section: DerivedSection,
    manifest: DocManifest,
    *,
    synthesize: bool,
    header: str,
    backrefs: dict[str, str] | None,
) -> tuple[str | _BulletSectionPart, bool, dict[str, str] | None]:
    """Render one derived section for a splice body.

    Shared by the single-region splice (:func:`project_splice_body`) and the
    multi-region path (:func:`project_region_bodies`). Returns
    ``(part, used_synthesis, backrefs)`` — ``backrefs`` is the lazily-loaded
    INCONSISTENCY backref cache, threaded through so a document with several
    bullets sections loads it once.
    """
    bullets = section.render == "bullets"
    particles = await _select_section_particles(
        session, section, use_embeddings=synthesize and not bullets
    )
    if bullets:
        if backrefs is None:
            backrefs = await get_inconsistency_backrefs(session)
        badges = await _bullet_badges(session, particles, backrefs)
        part = _bullet_section_part(
            section, particles, header=header, backrefs=backrefs, badges=badges
        )
        return part, False, backrefs
    if not particles:
        log.warning("projection: section %r selected no particles", section.title)
        return f"{header}_No current particles match this section's binding._\n", False, backrefs

    if synthesize:
        body, used = await _synthesised_section_body(
            session, section, particles, manifest.name, framing=manifest.framing
        )
    else:
        body, used = _deterministic_section_body(particles), False
    return f"{header}{body.rstrip()}\n", used, backrefs


async def project_region_bodies(
    session: AsyncSession,
    manifest: DocManifest,
    *,
    base_dir: Path,
    synthesize: bool,
    only_region: str | None = None,
) -> tuple[dict[str, str], bool]:
    """Render each region-bearing section's splice body separately.

    The multi-region half of the block-splice write mode: returns
    ``{region: body}`` in manifest order, each body headingless (the host
    file's hand-authored heading above the sentinels owns it) and wiki-link
    stripped, plus whether any section used LLM synthesis. ``only_region``
    restricts the render to one declared region (the ``--splice REGION``
    re-roll path on a region-bearing manifest).

    Raises ``ValueError`` when the manifest declares no regions, when
    ``only_region`` names an undeclared region, or — for the splice-all path
    (``only_region=None``) — when any derived section lacks a ``region``
    (a silently unspliced section is an authoring mistake, not a choice).
    The document budget is not applied on this path: no current
    region-bearing manifest sets one, and a budget spanning independently
    spliced regions has no defined truncation order.
    """
    regions = manifest.region_sections()
    if not regions:
        raise ValueError(f"manifest {manifest.name!r} declares no `region:` on any section")
    if only_region is not None and only_region not in regions:
        declared = ", ".join(regions)
        raise ValueError(
            f"manifest {manifest.name!r} declares no region {only_region!r} (declared: {declared})"
        )
    if only_region is None:
        unbound = [
            s.title for s in manifest.sections if isinstance(s, DerivedSection) and s.region is None
        ]
        if unbound:
            raise ValueError(
                f"--splice-all requires every derived section to declare a `region:`; "
                f"missing on: {', '.join(map(repr, unbound))}"
            )

    bodies: dict[str, str] = {}
    any_synth = False
    backrefs: dict[str, str] | None = None
    for region, section in regions.items():
        if only_region is not None and region != only_region:
            continue
        part, used, backrefs = await _derived_section_part(
            session,
            section,
            manifest,
            synthesize=synthesize,
            header="",
            backrefs=backrefs,
        )
        any_synth = any_synth or used
        body = part if isinstance(part, str) else part.render()
        bodies[region] = strip_wiki_links(body.rstrip("\n") + "\n")
    return bodies, any_synth


@dataclass(frozen=True)
class DriftResult:
    """Outcome of a drift-gate check."""

    drifted: bool
    snapshot_path: Path
    regenerated: str
    committed: str | None
    #: Region-trailer consistency failures: one message per
    #: declared region whose host-file ``<!-- sources -->`` trailer no longer
    #: matches the deterministic selection. Empty when the manifest declares no
    #: regions, the output file could not be resolved, or everything matches.
    region_issues: tuple[str, ...] = ()

    @property
    def reason(self) -> str:
        """A one-line operator explanation of the check outcome."""
        if self.region_issues:
            issues = "; ".join(self.region_issues)
            return (
                f"projected regions drifted from the store selection: {issues}. "
                "Re-splice with `particles project <manifest> --splice-all` and "
                "commit the re-blessed render."
            )
        if self.committed is None:
            return f"no committed snapshot at {self.snapshot_path} to diff against"
        if self.drifted:
            return (
                f"deterministic projection drifted from {self.snapshot_path}: the "
                "committed snapshot no longer matches the store + manifest (selection "
                "or structure changed). Regenerate with `particles project`."
            )
        return f"deterministic projection matches {self.snapshot_path}"


def snapshot_path_for(manifest: DocManifest, *, base_dir: Path) -> Path:
    """The committed deterministic-snapshot path the drift gate diffs.

    ``<base_dir>/<name>.snapshot.md`` — a sibling of the manifest. The snapshot is
    the gated contract (deterministic selection + structure); the human-facing
    ``output`` doc (LLM prose) is advisory (fork #3).
    """
    return base_dir / f"{manifest.name}.snapshot.md"


async def check_drift(
    session: AsyncSession,
    manifest: DocManifest,
    *,
    base_dir: Path,
    output_root: Path | None = None,
) -> DriftResult:
    """Regenerate the deterministic snapshot and diff it against the committed copy.

    No API key, no embedding model — the deterministic render is byte-stable for a
    given store, so this is the CI-runnable half of the gate.

    **Region-trailer consistency.** When the manifest declares
    sentinel regions and ``output_root`` is given, the check additionally parses
    the host output file and compares each declared region's ``<!-- sources -->``
    trailer id-set against that section's deterministic selection. A mismatch is
    a hard drift failure: a pin / store change must not stop at a refreshed
    snapshot — the shipped host document itself must be re-spliced (and that
    re-splice is the explicit re-blessing act). A relative ``output`` resolves
    against ``output_root`` (never the process cwd); ``output_root=None`` skips
    the region check for callers with no host-file anchor.
    """
    regenerated = (
        await project_document(session, manifest, base_dir=base_dir, synthesize=False)
    ).document
    snap_path = snapshot_path_for(manifest, base_dir=base_dir)
    committed = snap_path.read_text(encoding="utf-8") if snap_path.exists() else None

    region_issues = tuple(await _region_trailer_issues(session, manifest, output_root=output_root))
    drifted = committed is None or committed != regenerated or bool(region_issues)
    return DriftResult(
        drifted=drifted,
        snapshot_path=snap_path,
        regenerated=regenerated,
        committed=committed,
        region_issues=region_issues,
    )


def _trailer_short_ids(body: str) -> set[str] | None:
    """The ``p-<shortid>`` set from a region body's sources trailer, or None."""
    match = SOURCES_TRAILER_RE.search(body)
    if match is None:
        return None
    ids = {frag.strip() for frag in match.group("ids").split(",") if frag.strip()}
    return {_strip_pin_prefix(i) for i in ids}


async def _region_trailer_issues(
    session: AsyncSession,
    manifest: DocManifest,
    *,
    output_root: Path | None,
) -> list[str]:
    """Per-region trailer-vs-selection mismatches in the host file."""
    regions = manifest.region_sections()
    if not regions or output_root is None or manifest.output is None:
        return []
    out_path = Path(manifest.output)
    if not out_path.is_absolute():
        out_path = output_root / out_path
    if not out_path.exists():
        return [f"output file {out_path} not found (regions {', '.join(regions)} unchecked)"]

    host_regions = {r.region: r for r in find_projected_regions(out_path.read_text("utf-8"))}
    issues: list[str] = []
    for region, section in regions.items():
        host = host_regions.get(region)
        if host is None:
            issues.append(f"region {region!r} missing from {out_path.name}")
            continue
        selected = await _select_section_particles(session, section, use_embeddings=False)
        expected = {_short_id(p.id) for p, _eff in selected}
        found = _trailer_short_ids(host.body)
        if found is None:
            issues.append(f"region {region!r} in {out_path.name} has no sources trailer")
        elif found != expected:
            gone = ", ".join(sorted(expected - found)) or "-"
            extra = ", ".join(sorted(found - expected)) or "-"
            issues.append(
                f"region {region!r} in {out_path.name} cites a different claim set than "
                f"the store selection (missing: {gone}; extra: {extra})"
            )
    return issues
