"""Self-contained HTML assembly for the graph exporter.

One output file, no network: the vendored Cytoscape.js, the encoding styles, the glue script, and the :class:`GraphData` JSON payload are
all inlined, so the artifact opens over ``file://`` and works air-gapped.

Safety notes:
- The JSON payload is embedded in a ``<script type="application/json">`` block
  with ``</`` escaped (``<\\/`` — a no-op inside JSON strings), so particle
  content can never break out of the element.
- The glue script builds every panel element via ``textContent`` — particle
  content and subject names are untrusted text and are never interpolated into
  HTML. Source links render as anchors only for http(s) URIs.
- The vendored Cytoscape build is verified free of ``</script`` at test time
  (``tests/test_graph_exporter.py``), so verbatim inlining is safe.
"""

from __future__ import annotations

import html
import json
from datetime import datetime

from particles.core.schema import GraphData

from ._assets import CYTOSCAPE_VERSION, cytoscape_js, design_tokens_css

_LEGEND = (
    ("opacity", "effective confidence (computed at render time — decay is literal fading)"),
    ("solid / dashed / dotted", "ACTIVE / SUPERSEDED ghost / PROVENANCE_STALE"),
    ("☒", "RETRACTED tombstone"),
    ("⚠", "contested — hover or open the panel for the fired bases"),
    ("node size", "particles on the subject + utility evidence"),
    ("node shade", "best-supported claim on that subject (display aggregate)"),
    ("bold blue", "retrieval hit (query scope)"),
)

_TEMPLATE = """<!DOCTYPE html>
<!-- Generated by `particles export graph`.
     Vendored: Cytoscape.js __CY_VERSION__ (MIT, © The Cytoscape Consortium;
     license text ships in the SDK at artifacts/graph/LICENSE.cytoscape.txt). -->
<!-- data-theme="light" pins the design tokens' light palette: the encodings
     are calibrated against a light canvas (opacity = confidence must fade
     toward white), so the artifact never inherits a dark UA default. -->
<html lang="en" data-theme="light">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="generator" content="particles export graph">
<meta name="generated-at" content="__GENERATED_AT__">
<title>__TITLE__</title>
<!-- Design tokens (design/tokens.css), inlined so the artifact stays
     self-contained. Every colour below is a --p-* token. -->
<style>__DESIGN_TOKENS__</style>
<style>
  * { box-sizing: border-box; }
  body { margin: 0; font: 14px/1.45 var(--p-font-sans);
         color: var(--p-text); background: var(--p-surface);
         display: flex; flex-direction: column; height: 100vh; }
  header { padding: 10px 16px 8px; border-bottom: 1px solid var(--p-border); }
  header h1 { margin: 0 0 2px; font-size: 17px; }
  .meta { color: var(--p-text-muted); font-size: 12px; }
  .banner { margin-top: 6px; }
  .banner div { background: var(--p-amber-soft); border: 1px solid var(--p-amber);
                color: var(--p-amber); border-radius: var(--p-radius-xs);
                padding: 3px 8px; font-size: 12px; margin: 2px 0; }
  .legend { margin-top: 6px; color: var(--p-text-muted); font-size: 11.5px; }
  .legend span { margin-right: 12px; white-space: nowrap; }
  .legend b { color: var(--p-text); font-weight: 600; }
  #wrap { display: flex; flex: 1; min-height: 0; }
  #cy { flex: 1; min-width: 0; }
  #panel { width: 340px; border-left: 1px solid var(--p-border); overflow-y: auto;
           padding: 10px 12px; display: none; }
  #panel.open { display: block; }
  #panel h2 { font-size: 14px; margin: 0 0 4px; }
  #panel .sub { color: var(--p-text-muted); font-size: 12px; margin-bottom: 8px; }
  .prow { border: 1px solid var(--p-border); border-radius: var(--p-radius-sm);
          padding: 7px 8px; margin: 6px 0; }
  .prow.ghost { opacity: 0.62; border-style: dashed; }
  .prow.hit { border-color: var(--p-badge-hit); border-width: 2px; }
  .prow .content { margin-bottom: 4px; }
  .prow .kv { color: var(--p-text-muted); font-size: 11.5px; }
  .chip { display: inline-block; border-radius: var(--p-radius-xs); padding: 0 5px;
          font-size: 10.5px; margin-right: 5px; color: var(--p-on-status);
          background: var(--p-slate); vertical-align: 1px; }
  .chip.ACTIVE { background: var(--p-status-active); color: var(--p-on-accent); }
  .chip.SUPERSEDED { background: var(--p-status-superseded); }
  .chip.RETRACTED { background: var(--p-status-retracted); }
  .chip.PROVENANCE_STALE { background: var(--p-status-provenance-stale);
                           color: var(--p-on-accent); }
  .chip.contested { background: var(--p-badge-contested); color: var(--p-on-accent); }
  .chip.hitchip { background: var(--p-badge-hit); color: var(--p-on-accent); }
  .bar { height: 5px; background: var(--p-conf-track); border-radius: 3px; margin: 3px 0 1px; }
  .bar i { display: block; height: 100%; border-radius: 3px; background: var(--p-conf-fill); }
  .chain { font-size: 11.5px; color: var(--p-text-muted); margin-top: 3px; }
  .chain a { cursor: pointer; color: var(--p-accent); text-decoration: none; }
  #panel code { font-size: 11px; font-family: var(--p-font-mono); background: var(--p-surface-2);
                padding: 1px 4px; border-radius: 3px; user-select: all; }
  a.copyid { cursor: pointer; font-size: 11px; }
  label.hist { font-size: 12px; color: var(--p-text-muted); margin-left: 12px; }
  a { color: var(--p-accent); }
</style>
<script>__CYTOSCAPE_JS__</script>
</head>
<body>
<header>
  <h1>__TITLE__</h1>
  <div class="meta">__META__<label class="hist" id="hist-wrap" hidden>
    <input type="checkbox" id="hist-toggle" checked> show history (ghosts)</label></div>
  <div class="banner" id="banner"></div>
  <div class="legend">__LEGEND__</div>
</header>
<div id="wrap">
  <div id="cy"></div>
  <aside id="panel"></aside>
</div>
<script type="application/json" id="graph-data">__GRAPH_DATA_JSON__</script>
<script>
"use strict";
const DATA = JSON.parse(document.getElementById("graph-data").textContent);
const P = DATA.particles;

const banner = document.getElementById("banner");
for (const line of DATA.disclosures) {
  const d = document.createElement("div");
  d.textContent = "⚠ " + line;
  banner.appendChild(d);
}

// Supersession chain lookups (predecessor <-> successor), panel drill-downs.
const succOf = {}, predOf = {};
for (const s of DATA.supersessions) {
  succOf[s.predecessor_id] = s.successor_id;
  predOf[s.successor_id] = s.predecessor_id;
}

function nodeSize(mass, u) {
  // Structural mass (particles on the subject: cargo + incident edges) sets
  // the base scale; utility evidence (the size encoding) adds on
  // top. Both log-scaled and capped so a hub can't dwarf the render.
  return Math.round(22 + Math.min(30, 9 * Math.log1p(mass)) + Math.min(24, 12 * Math.log1p(u)));
}
// Cytoscape needs concrete colour strings, so read the design tokens off <html>.
function tok(name) {
  return getComputedStyle(document.documentElement).getPropertyValue(name).trim();
}
const C = {
  label: tok("--p-text"), nodeBorder: tok("--p-graph-node-border"),
  edge: tok("--p-graph-edge"), edgeGhost: tok("--p-graph-edge-ghost"),
  edgeLabel: tok("--p-badge-contested"), hit: tok("--p-badge-hit"),
  hue: tok("--p-graph-node-hue") || "214",
  lWeak: parseFloat(tok("--p-graph-node-l-weak")) || 88,
  lStrong: parseFloat(tok("--p-graph-node-l-strong")) || 48,
};
function nodeShade(m) {
  // Best-supported-claim aggregate -> fill lightness, ramping from the
  // --p-graph-node-l-weak end (paler = weaker support) to -l-strong.
  // Comma syntax: cytoscape's color parser rejects space-separated HSL.
  const t = Math.max(0, Math.min(1, m));
  return "hsl(" + C.hue + ", 45%, " + Math.round(C.lWeak + (C.lStrong - C.lWeak) * t) + "%)";
}
function edgeStyleFor(info) {
  if (info.status === "SUPERSEDED") return "dashed";
  if (info.status === "PROVENANCE_STALE") return "dotted";
  if (info.status === "RETRACTED") return "dashed";
  return "solid";
}

// Structural mass per subject — rendered particles touching it (cargo,
// including the truncated tail, plus incident edges); structural counting
// only, no epistemic math.
const massOf = {};
for (const n of DATA.nodes) {
  massOf[n.subject_id] = (n.cargo || []).length + (n.cargo_truncated || 0);
}
for (const e of DATA.edges) {
  if (!P[e.particle_id]) continue;
  massOf[e.source] = (massOf[e.source] || 0) + 1;
  massOf[e.target] = (massOf[e.target] || 0) + 1;
}

const elements = [];
for (const n of DATA.nodes) {
  elements.push({ group: "nodes", data: {
    id: n.subject_id, label: n.label + (n.contested ? " ⚠" : ""),
    hop: n.hop, size: nodeSize(massOf[n.subject_id] || 0, n.utility_score),
    shade: nodeShade(n.max_effective_confidence),
    border: n.hop === 0 ? 3 : 1.5,
  }});
}
DATA.edges.forEach((e, i) => {
  const info = P[e.particle_id];
  if (!info) return;
  elements.push({ group: "edges",
    classes: (info.ghost ? "ghost " : "") + (info.retrieval_hit ? "hit" : ""),
    data: {
      id: "e" + i, source: e.source, target: e.target, particleId: e.particle_id,
      opacity: Math.max(0.08, info.effective_confidence),
      lstyle: edgeStyleFor(info),
      label: info.contested ? "⚠" : (info.status === "RETRACTED" ? "☒" : ""),
    }});
});

const cy = cytoscape({
  container: document.getElementById("cy"),
  elements: elements,
  // Layout runs explicitly below (not via init options). fit:false is
  // load-bearing: the init layout runs asynchronously after the explicit
  // layout+fit below, and its default fit:true would reset the viewport.
  layout: { name: "preset", fit: false },
  style: [
    { selector: "node", style: {
        "label": "data(label)", "font-size": 11, "color": C.label,
        "text-valign": "bottom", "text-margin-y": 4, "text-wrap": "wrap", "text-max-width": 130,
        "width": "data(size)", "height": "data(size)",
        "background-color": "data(shade)", "border-width": "data(border)",
        "border-color": C.nodeBorder,
    }},
    { selector: "edge", style: {
        // Tight control-point step: a real store holds many parallel particles
        // between one subject pair, and the default 40px step fans them into
        // huge arcs that dominate the canvas.
        "curve-style": "bezier", "control-point-step-size": 12,
        "width": 2, "line-color": C.edge,
        "opacity": "data(opacity)", "line-style": "data(lstyle)",
        "label": "data(label)", "font-size": 12, "color": C.edgeLabel,
    }},
    { selector: "edge.hit", style: { "line-color": C.hit, "width": 3.5 } },
    { selector: "edge.ghost", style: { "line-color": C.edgeGhost } },
    { selector: ".hidden", style: { "display": "none" } },
  ],
});

// History toggle: ghosts render only while checked (one export, both views).
const ghostIds = Object.keys(P).filter(function (id) { return P[id].ghost; });
if (ghostIds.length) {
  document.getElementById("hist-wrap").hidden = false;
  document.getElementById("hist-toggle").addEventListener("change", function (ev) {
    cy.edges().forEach(function (e) {
      const info = P[e.data("particleId")];
      if (info && info.ghost) e.toggleClass("hidden", !ev.target.checked);
    });
    if (panelSubject) showSubject(panelSubject);
  });
}

// --- panel (all text via textContent: particle content is untrusted) -------
const panel = document.getElementById("panel");
let panelSubject = null;

function el(tag, cls, text) {
  const e = document.createElement(tag);
  if (cls) e.className = cls;
  if (text !== undefined) e.textContent = text;
  return e;
}

function chainOf(pid) {
  let head = pid;
  while (predOf[head]) head = predOf[head];
  const chain = [head];
  while (succOf[head]) { head = succOf[head]; chain.push(head); }
  return chain;
}

function particleRow(pid) {
  const info = P[pid];
  const row = el("div", "prow" + (info.ghost ? " ghost" : "") + (info.retrieval_hit ? " hit" : ""));
  const head = el("div");
  head.appendChild(el("span", "chip " + info.status, info.status));
  if (info.contested) {
    const c = el("span", "chip contested", "contested: " + info.contested.bases.join("+"));
    let t = "bases: " + info.contested.bases.join(", ");
    if (info.contested.inconsistency_id) t += "\\nINCONSISTENCY " + info.contested.inconsistency_id;
    if (info.contested.caveat) t += "\\n" + info.contested.caveat;
    c.title = t;
    head.appendChild(c);
  }
  if (info.retrieval_hit) head.appendChild(el("span", "chip hitchip", "retrieval hit"));
  row.appendChild(head);
  row.appendChild(el("div", "content", (info.status === "RETRACTED" ? "☒ " : "") + info.content));
  const bar = el("div", "bar");
  const fill = el("i");
  fill.style.width = Math.round(100 * info.effective_confidence) + "%";
  fill.style.opacity = String(Math.max(0.25, info.effective_confidence));
  bar.appendChild(fill);
  row.appendChild(bar);
  row.appendChild(el("div", "kv",
    "confidence " + info.confidence.toFixed(2) + " → effective " +
    info.effective_confidence.toFixed(2) +
    (info.utility_score > 0 ? " · utility " + info.utility_score.toFixed(1) : "") +
    " · asserted " + String(info.asserted_at).slice(0, 10)));
  if (info.as_of_note) {
    row.appendChild(el("div", "kv", "as-of note: since retired (" + info.as_of_note.status +
      ", " + String(info.as_of_note.retired_at).slice(0, 10) + ", basis: " +
      info.as_of_note.basis + ")"));
  }
  const chain = chainOf(pid);
  if (chain.length > 1) {
    const c = el("div", "chain", "chain: ");
    chain.forEach(function (cid, i) {
      if (i) c.appendChild(document.createTextNode(" ⟶ "));
      const a = el("a", cid === pid ? "here" : "",
        cid.slice(0, 8) + (cid === pid ? " (this)" : ""));
      a.addEventListener("click", function () { showParticle(cid); });
      c.appendChild(a);
    });
    row.appendChild(c);
  }
  if (info.source_uri && /^https?:\\/\\//.test(info.source_uri)) {
    const kv = el("div", "kv");
    const a = el("a", "", "source");
    a.href = info.source_uri; a.rel = "noopener noreferrer"; a.target = "_blank";
    kv.appendChild(a);
    row.appendChild(kv);
  } else if (info.source_uri) {
    row.appendChild(el("div", "kv", "source: " + info.source_uri));
  }
  if (info.subject_ids.length > 2) {
    row.appendChild(el("div", "kv", "spans " + info.subject_ids.length +
      " subjects (drawn as a pairwise clique)"));
  }
  return row;
}

function showParticle(pid) {
  panelSubject = null;
  panel.className = "open";
  panel.replaceChildren(el("h2", "", "Particle " + pid.slice(0, 8)), particleRow(pid));
}

function showSubject(sid) {
  const n = DATA.nodes.find(function (x) { return x.subject_id === sid; });
  if (!n) return;
  panelSubject = sid;
  panel.className = "open";
  const showGhosts = ghostIds.length === 0 || document.getElementById("hist-toggle").checked;
  panel.replaceChildren();
  panel.appendChild(el("h2", "", n.label));
  // The subject id is the --subject input for re-anchoring the render here.
  const idRow = el("div", "sub");
  idRow.appendChild(el("code", "", n.subject_id));
  const copyLink = el("a", "copyid", "copy");
  copyLink.addEventListener("click", function () {
    try {
      navigator.clipboard.writeText(n.subject_id);
      copyLink.textContent = "copied";
      setTimeout(function () { copyLink.textContent = "copy"; }, 1200);
    } catch (err) {
      window.getSelection().selectAllChildren(idRow.querySelector("code"));
    }
  });
  idRow.appendChild(document.createTextNode(" "));
  idRow.appendChild(copyLink);
  panel.appendChild(idRow);
  panel.appendChild(el("div", "sub",
    (n.subject_class ? n.subject_class + " · " : "") + "hop " + n.hop +
    " · best-supported claim " + n.max_effective_confidence.toFixed(2) +
    (n.utility_score > 0 ? " · utility evidence " + n.utility_score.toFixed(1) : "")));
  let listed = 0;
  for (const pid of n.cargo) {
    const info = P[pid];
    if (!info || (info.ghost && !showGhosts)) continue;
    panel.appendChild(particleRow(pid));
    listed += 1;
  }
  const edgeParticles = Object.keys(P).filter(function (pid) {
    return P[pid].subject_ids.length >= 2 && P[pid].subject_ids.indexOf(sid) !== -1 &&
      (showGhosts || !P[pid].ghost);
  });
  if (edgeParticles.length) {
    panel.appendChild(el("div", "sub", "edges (multi-subject particles):"));
    for (const pid of edgeParticles) panel.appendChild(particleRow(pid));
  }
  if (n.cargo_truncated > 0) {
    panel.appendChild(el("div", "sub", "⚠ " + n.cargo_truncated +
      " more particle(s) beyond the panel cap — raise " +
      "graph.max_particles_per_subject to see them"));
  }
  if (!listed && !edgeParticles.length)
    panel.appendChild(el("div", "sub", "no particles on this lens"));
}

// Deterministic layout + fit: run the (non-animated, synchronous) layout
// explicitly, then fit — no event racing with the init-time layout. The
// window-load refit covers a flex container whose final size lands late.
// nodeDimensionsIncludeLabels + spacing keep wrapped labels from piling into
// each other on real stores. Query scope uses a circle (element order =
// retrieval rank, clockwise): grid stacks nodes into one cell when labels
// are large, and a circle keeps every label clear of its neighbours.
const LAYOUT = DATA.scope_type === "subject"
  ? { name: "concentric", concentric: function (n) { return 10 - n.data("hop"); },
      levelWidth: function () { return 1; }, minNodeSpacing: 60, animate: false,
      nodeDimensionsIncludeLabels: true, fit: false }
  : { name: "circle", animate: false, spacingFactor: 1.2,
      nodeDimensionsIncludeLabels: true, fit: false };
function refit() { cy.resize(); cy.fit(undefined, 30); }
cy.layout(LAYOUT).run();
// cy.fit() silently no-ops until the renderer is actually ready (observed:
// zoom stays exactly 1 / pan 0,0 through ready, load, and the first render
// event), so verify the fit took and retry per frame until it does. A real
// fit never lands on exactly zoom 1 + pan (0,0), so the check is safe.
let fitTries = 0;
(function fitLoop() {
  refit();
  fitTries += 1;
  const untouched = cy.zoom() === 1 && cy.pan().x === 0 && cy.pan().y === 0;
  if (untouched && fitTries < 300) requestAnimationFrame(fitLoop);
})();

cy.on("tap", "node", function (ev) { showSubject(ev.target.id()); });
cy.on("tap", "edge", function (ev) { showParticle(ev.target.data("particleId")); });
cy.on("tap", function (ev) {
  if (ev.target === cy) { panel.className = ""; panelSubject = null; }
});
</script>
</body>
</html>
"""


def render_html(data: GraphData, *, generated_at: datetime) -> str:
    """Assemble the single self-contained HTML artifact for one render."""
    if data.scope_type == "subject":
        anchor = next((n for n in data.nodes if n.subject_id == data.scope_ref), None)
        title = f"Particles graph — {anchor.label if anchor else data.scope_ref}"
    else:
        title = f"Particles graph — query: {data.scope_ref}"

    meta_bits = [
        f"{len(data.nodes)} subjects · {len(data.edges)} edges · {len(data.particles)} particles",
        data.census.scope,
    ]
    if data.as_of is not None:
        meta_bits.append(f"as of {data.as_of.isoformat()}")
    meta_bits.append(f"rendered {generated_at.isoformat(timespec='seconds')}")

    legend = "".join(
        f"<span><b>{html.escape(mark)}</b> {html.escape(meaning)}</span>"
        for mark, meaning in _LEGEND
    )

    payload = json.dumps(
        data.model_dump(mode="json"), ensure_ascii=False, separators=(",", ":")
    ).replace("</", "<\\/")

    return (
        _TEMPLATE.replace("__CY_VERSION__", CYTOSCAPE_VERSION)
        .replace("__GENERATED_AT__", generated_at.isoformat(timespec="seconds"))
        .replace("__TITLE__", html.escape(title))
        .replace("__META__", html.escape(" · ".join(meta_bits)))
        .replace("__LEGEND__", legend)
        .replace("__CYTOSCAPE_JS__", cytoscape_js())
        # `</` cannot occur in a stylesheet of custom properties, but guard the
        # element boundary anyway — same discipline as the JSON payload.
        .replace("__DESIGN_TOKENS__", design_tokens_css().replace("</", "<\\/"))
        .replace("__GRAPH_DATA_JSON__", payload)
    )
