/*
 * esbuild config for the unified Particles web UI.
 *
 * Bundles src/main.ts → dist/app.js and copies the static shell (index.html,
 * manifest.webmanifest, service-worker.js, styles.css) plus the vendored
 * Cytoscape.js (artifacts/graph/ — the same build the graph exporter embeds;
 * same-origin asset, no CDN) and the design-system tokens
 * (design/tokens.css) into dist/. The engine serves
 * dist/ same-origin at GET /app, so the app's authenticated
 * fetch calls to /curation, /query, /graph, … trigger no CORS preflight.
 *
 *   node esbuild.config.mjs              # watch build for local development
 *   node esbuild.config.mjs production   # one-shot minified build
 *
 * Run `npm run build`, which first runs `npm run gen-api` to regenerate
 * src/openapi.d.ts from ../../artifacts/openapi.json so the typed
 * client never drifts from the committed contract.
 *
 * dist/ is COMMITTED: `git pull` delivers the working bundle,
 * so operators never need npm — only UI development does. A change under
 * src/ or public/ (or to the vendored Cytoscape / the OpenAPI contract)
 * must therefore commit the rebuilt dist/ alongside it.
 */
import esbuild from "esbuild";
import process from "process";
import { createHash } from "crypto";
import { cpSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "fs";

const production = process.argv[2] === "production";
const OUTDIR = "dist";

// A per-build version string: the package version plus a hash of the build
// INPUTS (src/, public/, the vendored Cytoscape, package.json). Injected into
// the bundle (__BUILD_VERSION__) for the diagnostics footer AND into the
// service worker's cache name, so a changed build busts the app-shell cache
//. Deliberately deterministic — no timestamp — so rebuilding
// identical sources yields a byte-identical dist/ and the committed bundle
// only ever changes when the code does.
const pkg = JSON.parse(readFileSync("package.json", "utf8"));

function hashInputs() {
  const files = [];
  const walk = (p) => {
    if (statSync(p).isDirectory()) {
      for (const name of readdirSync(p).sort()) walk(`${p}/${name}`);
    } else {
      files.push(p);
    }
  };
  for (const root of [
    "src",
    "public",
    "package.json",
    "../../artifacts/graph/cytoscape.min.js",
    "../../design/tokens.css",
  ]) {
    walk(root);
  }
  const h = createHash("sha256");
  for (const f of files.sort()) {
    h.update(f);
    h.update("\0");
    h.update(readFileSync(f));
  }
  return h.digest("hex").slice(0, 12);
}

const BUILD_VERSION = `${pkg.version}+${hashInputs()}`;

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
Source under src/; see clients/web-ui/README.md.
*/`;

mkdirSync(OUTDIR, { recursive: true });

// Copy the static app shell into dist/ (the engine serves dist/ wholesale).
function copyShell() {
  for (const f of ["index.html", "manifest.webmanifest", "styles.css", "icon.svg"]) {
    cpSync(`public/${f}`, `${OUTDIR}/${f}`);
  }
  // Vendor the SAME Cytoscape.js build the static graph exporter embeds
  // (the version is pinned and same-origin serving required —
  // no CDN). The #/graph route loads it with a plain <script src> at runtime.
  cpSync("../../artifacts/graph/cytoscape.min.js", `${OUTDIR}/cytoscape.min.js`);
  cpSync("../../artifacts/graph/LICENSE.cytoscape.txt", `${OUTDIR}/LICENSE.cytoscape.txt`);
  // The design-system tokens (design/tokens.css — the single source for
  // colour / type / space across every Particles surface). styles.css only
  // aliases onto the --p-* variables it defines; index.html loads it first.
  // Same cross-directory pattern as the vendored Cytoscape above.
  cpSync("../../design/tokens.css", `${OUTDIR}/tokens.css`);
  // The service worker is templated: stamp the build version into its cache
  // name so a new build invalidates the old app-shell cache.
  const sw = readFileSync("public/service-worker.js", "utf8").replaceAll(
    "__BUILD_VERSION__",
    BUILD_VERSION,
  );
  writeFileSync(`${OUTDIR}/service-worker.js`, sw);
}

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  format: "esm",
  target: "es2020",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  outfile: `${OUTDIR}/app.js`,
  minify: production,
  define: { __BUILD_VERSION__: JSON.stringify(BUILD_VERSION) },
});

copyShell();

if (production) {
  await context.rebuild();
  await context.dispose();
  process.exit(0);
} else {
  await context.watch();
}
