"""Regenerate ``tests/dogfood/llm_responses.yaml`` from a live LLM run.

A developer command was deferred that runs the dogfood corpus through the
**real** synthesis + Layer-B judge pipeline once and records the responses, so
maintainers do not hand-edit ``llm_responses.yaml`` when a synthesis/judge
prompt legitimately changes.

It lives here — invoked as ``python -m tests.dogfood.record`` — rather than as
a ``particles`` CLI verb, because the dogfood corpus and its loader live in the
test tree, outside the shipped ``particles`` package; a library verb that
imported ``tests.dogfood`` would couple the package to its tests and break a
packaged install.

Usage::

    uv run python -m tests.dogfood.record            # prompts for confirmation
    uv run python -m tests.dogfood.record --yes       # skip the cost prompt
    uv run python -m tests.dogfood.record --dry-run    # show changes, write nothing

Makes real Anthropic API calls (needs ``ANTHROPIC_API_KEY``). Cost is small —
the corpus has a handful of subjects above the synthesis threshold — but it is
real spend, hence the confirmation prompt.

**Comment loss:** the regenerated file is ``yaml.safe_dump``-ed, so per-entry
comments in the prior file are not preserved (a fixed header is re-emitted).
Re-add any explanatory comments by hand after a regeneration if needed. The
run **merges** into the existing file: subjects that synthesised this run are
overwritten; any other top-level keys (e.g. below-threshold sanity hooks) are
preserved.
"""

from __future__ import annotations

import argparse
import asyncio
import os
import sys
import tempfile
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import yaml

from particles.core.status import Status
from particles.render.article_synthesis import _parse_layer_b_verdicts
from particles.secrets import get_anthropic_api_key_optional
from tests.dogfood import (
    _JUDGE_PAIR_PARTICLE_RE,
    _LLM_RESPONSES_PATH,
    _SUBJECT_LINE_RE,
    DogfoodSubject,
    load_corpus,
    persist_corpus,
)

_HEADER = """\
# Mock LLM responses for the dogfood corpus.
#
# GENERATED by `python -m tests.dogfood.record` — see tests/dogfood/AGENTS.md.
# Per-subject entries are {synthesis, judge_verdicts}; the `{p0}`/`{p1}` …
# placeholders in `synthesis` reference particles in corpus.yaml declaration
# order and are substituted with the actual short IDs at fixture-load time.
# Hand-add explanatory comments after regenerating — they are not preserved.
"""


class _RecordingClient:
    """Anthropic-shaped proxy that passes calls through to the real client and
    records every ``(prompt, response_text)`` pair for later reconstruction.

    The inverse of :func:`tests.dogfood.build_mock_client`: that *replays*
    canned text keyed on the prompt; this *captures* the real text so a fresh
    set of canned responses can be written.
    """

    def __init__(self, real: Any) -> None:
        self._real = real
        self.calls: list[tuple[str, str]] = []
        self.messages = SimpleNamespace(create=self._create)

    def _create(self, **kwargs: Any) -> Any:
        resp = self._real.messages.create(**kwargs)
        prompt = str(kwargs["messages"][0]["content"])
        text = str(resp.content[0].text)
        self.calls.append((prompt, text))
        return resp


def reconstruct_responses(
    subjects: list[DogfoodSubject],
    recorded: list[tuple[str, str]],
) -> dict[str, dict[str, Any]]:
    """Rebuild the per-subject ``{synthesis, judge_verdicts}`` mapping from the
    recorded ``(prompt, text)`` calls.

    Pure (no I/O) so it can be unit-tested without a live run. Mirrors the
    recognition logic in :func:`tests.dogfood.build_mock_client`:

    * A **synthesis** call carries a ``SUBJECT: <name>`` line. Its response body
      has each active particle's 8-char short ID replaced with the matching
      ``{pN}`` placeholder (N = the particle's position among the subject's
      active particles), so the body re-templates cleanly on the next fixture
      load when the IDs are different.
    * A **judge** call carries a ``PAIRS:`` block; the subject is recovered from
      the first cited short ID and the response is parsed into the
      ``[{id, verdict, reason}, …]`` verdict array.

    Later calls win, so the final accepted synthesis / judge response for a
    subject is what is recorded (Layer-A / Layer-B retries overwrite earlier
    attempts).
    """
    short_to_subject: dict[str, str] = {}
    active_by_subject: dict[str, list[Any]] = {}
    for ds in subjects:
        active = [p for p in ds.particles if p.status == Status.ACTIVE]
        active_by_subject[ds.subject.canonical_name] = active
        for p in active:
            short_to_subject[p.id[:8]] = ds.subject.canonical_name

    out: dict[str, dict[str, Any]] = {}
    for prompt, text in recorded:
        if "PAIRS:" in prompt:
            m = _JUDGE_PAIR_PARTICLE_RE.search(prompt)
            if m is None:
                continue
            name = short_to_subject.get(m.group(1).lower())
            if name is None:
                continue
            verdicts = _parse_layer_b_verdicts(text)
            if verdicts is not None:
                out.setdefault(name, {})["judge_verdicts"] = verdicts
        else:
            m = _SUBJECT_LINE_RE.search(prompt)
            if m is None:
                continue
            name = m.group(1)
            templated = text
            for idx, p in enumerate(active_by_subject.get(name, [])):
                templated = templated.replace(p.id[:8], "{p" + str(idx) + "}")
            out.setdefault(name, {})["synthesis"] = templated
    return out


def _merge_into_existing(
    regenerated: dict[str, dict[str, Any]], path: Path
) -> dict[str, dict[str, Any]]:
    """Overlay ``regenerated`` onto the prior file's data, preserving keys not
    touched this run (e.g. below-threshold sanity hooks)."""
    merged: dict[str, dict[str, Any]] = {}
    if path.exists():
        prior = yaml.safe_load(path.read_text()) or {}
        if isinstance(prior, dict):
            merged.update({str(k): v for k, v in prior.items()})
    merged.update(regenerated)
    return merged


def _dump(data: dict[str, dict[str, Any]]) -> str:
    body = yaml.safe_dump(data, sort_keys=True, allow_unicode=True, default_flow_style=False)
    return f"{_HEADER}\n{body}"


async def _run(recorder: _RecordingClient) -> list[DogfoodSubject]:
    """Persist the dogfood corpus into a throwaway store and drive a real wiki
    synthesis run, populating ``recorder.calls`` as a side effect."""
    import particles._orm_modules  # noqa: F401 — register every ORM's metadata
    from particles.db import Base, get_engine, session_scope
    from particles.exporters.wiki import WikiExporter

    subjects = load_corpus()
    engine = get_engine()
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    async with session_scope() as session:
        await persist_corpus(session, subjects)
    with tempfile.TemporaryDirectory() as wiki_dir:
        async with session_scope() as session:
            await WikiExporter().export(session, Path(wiki_dir))
    return subjects


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m tests.dogfood.record",
        description="Regenerate tests/dogfood/llm_responses.yaml from a live LLM run.",
    )
    parser.add_argument("--yes", "-y", action="store_true", help="Skip the cost confirmation.")
    parser.add_argument(
        "--dry-run", action="store_true", help="Show the regenerated subjects; write nothing."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=_LLM_RESPONSES_PATH,
        help="Destination YAML (default: tests/dogfood/llm_responses.yaml).",
    )
    args = parser.parse_args(argv)

    if get_anthropic_api_key_optional() is None:
        print("ANTHROPIC_API_KEY is not set — this command makes real LLM calls.", file=sys.stderr)
        return 2

    if not args.yes and not args.dry_run:
        reply = input("This makes real Anthropic API calls (small cost). Proceed? [y/N] ")
        if reply.strip().lower() not in ("y", "yes"):
            print("Aborted.")
            return 1

    import anthropic

    from particles.llm import set_client
    from particles.secrets import get_anthropic_api_key

    # Point every store operation at a throwaway DB so the operator's real
    # store is never touched. Set before the lazy engine is first built.
    with tempfile.TemporaryDirectory() as db_dir:
        os.environ["DATABASE_URL"] = f"sqlite+aiosqlite:///{Path(db_dir) / 'dogfood.db'}"
        from particles.db import reset_engine

        reset_engine()
        recorder = _RecordingClient(anthropic.Anthropic(api_key=get_anthropic_api_key()))
        set_client(recorder)
        try:
            subjects = asyncio.run(_run(recorder))
        finally:
            set_client(None)
            reset_engine()
            os.environ.pop("DATABASE_URL", None)

    regenerated = reconstruct_responses(subjects, recorder.calls)
    if not regenerated:
        print("No synthesis responses were recorded — nothing to write.", file=sys.stderr)
        return 1

    merged = _merge_into_existing(regenerated, args.output)
    rendered = _dump(merged)

    print(f"Recorded {len(regenerated)} subject(s): {', '.join(sorted(regenerated))}")
    if args.dry_run:
        print("--dry-run: not writing. Rendered output below:\n")
        print(rendered)
        return 0

    args.output.write_text(rendered, encoding="utf-8")
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
